services:
  - type: web
    name: findit-ia
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: MODELO_PATH
        value: modelo_findit.pkl
